### ISSUE TITLE
Has this model been published in any papers? I would like to know the effect comparison with other DTA models

### ISSUE THREAD

**Issue by ljxabc** [daydayupzzl/HeteroDTA#1]

**Comment by daydayupzzl** [comment]
Thank you for your interest in our model! Yes, the model has been published in the following paper:
Zhang Z, He X, Long D, Luo G, Chen S. Enhancing generalizability and performance in drug-target interaction identification by integrating pharmacophore and pre-trained models. Bioinformatics. 2024 Jun 28;40(Suppl 1):i539-i547. doi: 10.1093/bioinformatics/btae240. PMID: 38940179; PMCID: PMC11211825. In the paper, we provide a detailed performance comparison with existing DTA models across multiple benchmark datasets. Thanks again for your interest.
